export const ProvidersType = {
  CREATE_PROVIDER_START: 'CREATE_PROVIDER_START',
  CREATE_PROVIDER_SUCCESS: 'CREATE_PROVIDER_SUCCESS',
  CREATE_PROVIDER_FAILURE: 'CREATE_PROVIDER_FAILURE',
  GET_PROVIDER_LIST_START: 'GET_PROVIDER_LIST_START',
  GET_PROVIDER_LIST_SUCCESS: 'GET_PROVIDER_LIST_SUCCESS',
  GET_PROVIDER_LIST_FAILURE: 'GET_PROVIDER_LIST_FAILURE',
}