export const ProductsTypes = {
  GET_PRODUCTS_LIST_START: 'GET_PRODUCTS_LIST_START',
  GET_PRODUCTS_LIST_SUCCESS: 'GET_PRODUCTS_LIST_SUCCESS',
  GET_PRODUCTS_LIST_FAILURE: 'GET_PRODUCTS_LIST_FAILURE',
}