const UserTypes = {
  REGISTER_USER_START: 'REGISTER_USER_START',
  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',
}

export default UserTypes;