const UserTypes = {
  REGISTER_USER_START: 'REGISTER_USER_START',
  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',
  USER_SIGN_OUT_SUCCESS: 'USER_SIGN_OUT_SUCCESS',
  USER_SIGN_OUT_FAILURE: 'USER_SIGN_OUT_FAILURE',
  CHECKING_USER_AUTH_START: 'CHECKING_USER_AUTH_START',
  CHECKING_USER_AUTH_SUCCESS: 'CHECKING_USER_AUTH_SUCCESS',
  CHECKING_USER_AUTH_FAILURE: 'CHECKING_USER_AUTH_FAILURE'
}

export default UserTypes;